# Generated by Django 4.2.8 on 2026-08-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_make_student_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='auto_marked',
            field=models.BooleanField(default=False, verbose_name='Auto Marked'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='login_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Login Time'),
        ),
    ]
