# Generated by Django 4.2.8 on 2026-08-18 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_add_auto_attendance_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
