# Generated by Django 4.2.8 on 2026-09-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parent Name'),
        ),
    ]
