# Generated by Django 4.2.8 on 2026-09-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_make_parent_name_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fee', 'verbose_name_plural': 'Fees'},
        ),
        migrations.AlterField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
    ]
