# Generated by Django 4.2.8 on 2026-09-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_make_due_date_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_field',
            field=models.CharField(choices=[('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8')], default='8', max_length=1, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='joining_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Parent Mobile'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Phone'),
        ),
    ]
