# Generated by Django 4.2.8 on 2026-09-11 07:08

import django.core.validators
from django.db import migrations, models


def update_quizzes_to_20_percent(apps, schema_editor):
    Quiz = apps.get_model('app', 'Quiz')
    QuizResult = apps.get_model('app', 'QuizResult')
    # Set all quizzes to 20% passing
    Quiz.objects.all().update(passing_percentage=20)
    # Set all results >= 20% to passed=True
    QuizResult.objects.filter(percentage__gte=20).update(passed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_sync_student_passwords_to_gr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='passing_percentage',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Passing Percentage'),
        ),
        migrations.RunPython(update_quizzes_to_20_percent, reverse_code=migrations.RunPython.noop),
    ]

