# Generated by Django 4.2.8 on 2026-09-12 04:16

from django.db import migrations, models


def backfill_fee_month_year(apps, schema_editor):
    """Set fee_month and fee_year from created_at for all existing fee records."""
    Fee = apps.get_model('app', 'Fee')
    for fee in Fee.objects.all():
        fee.fee_month = fee.created_at.month
        fee.fee_year = fee.created_at.year
        fee.save(update_fields=['fee_month', 'fee_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_single_computer_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_month',
            field=models.IntegerField(
                choices=[
                    (1, 'January (જાન્યુઆરી)'), (2, 'February (ફેબ્રુઆરી)'),
                    (3, 'March (માર્ચ)'), (4, 'April (એપ્રિલ)'),
                    (5, 'May (મે)'), (6, 'June (જૂન)'),
                    (7, 'July (જુલાઈ)'), (8, 'August (ઓગસ્ટ)'),
                    (9, 'September (સપ્ટેમ્બર)'), (10, 'October (ઓક્ટોબર)'),
                    (11, 'November (નવેમ્બર)'), (12, 'December (ડિસેમ્બર)'),
                ],
                default=1,
                verbose_name='Fee Month (કઈ ફી)',
            ),
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_year',
            field=models.IntegerField(default=2026, verbose_name='Fee Year (વર્ષ)'),
        ),
        migrations.RunPython(backfill_fee_month_year, reverse_code=migrations.RunPython.noop),
    ]
